### ISSUE TITLE
Branching evolution

### ISSUE THREAD

**Issue by underbais** [hchyang/CSiTE#1]
Hello,

Is it capable of generating simulated branching (non-linear) evolution WES data?

Thanks

**Comment by hchyang** [comment]
> Hello,
> 
> Is it capable of generating simulated branching (non-linear) evolution WES data?
> 
> Thanks

Yes, it can take a phylogenetic tree as input and simulate WES data. But itself can not simulate the tree. You need to simulate the tree using other tools, e.g. ms. You can find some examples in the Tutorial section of our manual and the Supp of our paper (https://doi.org/10.1093/bioinformatics/btz028).
